listener 8081
protocol mqtt

listener 8082
protocol websockets

allow_anonymous false
password_file E:\\pandownload1\\ML\\Police\\Project\\submodules\\mosquitto\\passwd\\passwd

log_dest file E:\\pandownload1\\ML\\Police\\Project\\submodules\\mosquitto\\log\\mosquitto.log

log_type error
log_type warning
log_type notice
# log_type debug

max_connections 100
max_inflight_messages 20
max_queued_messages 100